version: "3"

networks:
  sm-net:
    external: true

services:
  minio1:
    image: minio/minio
    hostname: minio1
    command: server http://minio{1...2}/data
    environment:
    - MINIO_ROOT_USER=minioadmin
    - MINIO_ROOT_PASSWORD=minioadmin
#    secrets:
#      - secret_key
#      - access_key
    volumes:
    - /opt/minio/minio1/data:/data
    ports:
    - 9000:9000
    networks:
    - sm-net
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      mode: replicated
#      placement:
#        constraints:
#        - node.labels.minio1 == true
#        - node.role == manager
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  minio2:
    image: minio/minio
    hostname: minio2
    command: server http://minio{1...2}/data
    environment:
    - MINIO_ROOT_USER=minioadmin
    - MINIO_ROOT_PASSWORD=minioadmin
#    secrets:
#      - secret_key
#      - access_key
    volumes:
    - /opt/minio/minio2/data:/data
    ports:
    - 9002:9000
    networks:
    - sm-net
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
      mode: replicated
#      placement:
#        constraints:
#        - node.labels.minio2 == true
#        - node.role == manager
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
#secrets:
#  secret_key:
#    external: true
#  access_key:
#    external: true