version: "3"

networks:
  sm-net:
    external: true

services:
  thumbor:
    image: minimalcompact/thumbor
    ports:
    - 8888:80
    networks:
    - sm-net
    deploy:
      mode: replicated
#      resources:
#        limits:
#          memory: 1g
#      placement:
#        constraints:
#        - node.labels.thumbor == true
#        - node.role == manager


