{{- if .Values.ingress.enabled -}}
  {{- $host := .Values.ingress.host -}}
  {{- $path := .Values.ingress.path -}}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end }}
  name: chaosblade-box
spec:
  rules:
    - host: {{ $host }}
      http:
        paths:
        - path: {{ $path }}
          pathType: Prefix
          backend:
            service:
              name: chaosblade-box
              port:
                number: 8080
{{- end -}}