# 通过 ingress 的 ConfigMap 可直接代理 mysql 的 tcp 端口，如：30006代理主库的3306 30008代理从库的3306

# 必须要有 write-mysql-svc 这个 service 供 master的 StatefulSet 使用
kind: Service
apiVersion: v1
metadata:
  name: write-mysql-svc
  labels:
    relate: master
    db: mysql
    env: dev
spec:
  selector:
    db: mysql
    env: dev
    relate: master
  clusterIP: None
  ports:
  - name: mysql
    port: 3306
  - name: exporter
    port: 9104
---
# Client service for connecting to any MySQL instance for reads.
# For writes, you must instead connect to the master: mysql-0.mysql.
# 必须要有 read-mysql-svc 这个 service 供 slave StatefulSet 使用
apiVersion: v1
kind: Service
metadata:
  name: read-mysql-svc
  labels:
    db: mysql
    env: dev
    relate: slave
spec:
  selector:
    db: mysql
    env: dev
    relate: slave
  clusterIP: None
  ports:
  - name: mysql
    port: 3306
  - name: exporter
    port: 9104
