version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - /opt/mysql/docker-my.cnf:/etc/mysql/conf.d/my.cnf
      - /opt/mysql/logs:/logs
      - /opt/mysql/data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
