apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: nacos
    release: kube-prometheus-stack
  name: nacos
  namespace: monitoring
spec:
  endpoints:
    - port: http
      path: /nacos/actuator/prometheus
  namespaceSelector:
    matchNames:
      - dev
  selector:
    matchLabels:
      app: nacos